In [38]:
import pandas as pd
import numpy as np

In [39]:
data_df = pd.read_csv("../data/raw/Customer-Churn.csv")

customer_df = data_df.copy()

In [40]:
data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [41]:
customer_df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [42]:
customer_df.shape

(7043, 21)

In [43]:
customer_df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [44]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [45]:
for column in customer_df.columns:
    print(f"la columna {column} cuenta con : {customer_df[column].nunique()}")
    print(f"{customer_df[column].unique()}\n\n")

la columna customerID cuenta con : 7043
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str


la columna gender cuenta con : 2
<StringArray>
['Female', 'Male']
Length: 2, dtype: str


la columna SeniorCitizen cuenta con : 2
[0 1]


la columna Partner cuenta con : 2
<StringArray>
['Yes', 'No']
Length: 2, dtype: str


la columna Dependents cuenta con : 2
<StringArray>
['No', 'Yes']
Length: 2, dtype: str


la columna tenure cuenta con : 73
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]


la columna PhoneService cuenta con : 2
<StringArray>
['No', 'Yes']
Length: 2, dtype: str


la columna MultipleLines cuenta con : 3
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str


la columna InternetService cuenta con : 3
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str


la columna OnlineSecurity cuenta con : 3
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


la columna OnlineBackup cuenta con : 3
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str


la columna DeviceProtection cuenta con : 3
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


la columna TechSupport cuenta con : 3
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


la columna StreamingTV cuenta con : 3
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


la columna StreamingMovies cuenta con : 3
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str


la columna Contract cuenta con : 3
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str


la columna PaperlessBilling cuenta con : 2
<StringArray>
['Yes', 'No']
Length: 2, dtype: str


la columna PaymentMethod cuenta con : 4
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str


la columna MonthlyCharges cuenta con : 1585
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]


la columna TotalCharges cuenta con : 6531
<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str


la columna Churn cuenta con : 2
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [46]:
for columna in customer_df.columns:
    duplicados = customer_df.duplicated().sum()
    nulls = customer_df[columna].isna().sum()
    print(f"la columna : {columna} tiene {duplicados} duplicados y {nulls} nulos ")

la columna : customerID tiene 0 duplicados y 0 nulos
la columna : gender tiene 0 duplicados y 0 nulos
la columna : SeniorCitizen tiene 0 duplicados y 0 nulos

la columna : Partner tiene 0 duplicados y 0 nulos
la columna : Dependents tiene 0 duplicados y 0 nulos
la columna : tenure tiene 0 duplicados y 0 nulos
la columna : PhoneService tiene 0 duplicados y 0 nulos
la columna : MultipleLines tiene 0 duplicados y 0 nulos
la columna : InternetService tiene 0 duplicados y 0 nulos
la columna : OnlineSecurity tiene 0 duplicados y 0 nulos
la columna : OnlineBackup tiene 0 duplicados y 0 nulos
la columna : DeviceProtection tiene 0 duplicados y 0 nulos
la columna : TechSupport tiene 0 duplicados y 0 nulos
la columna : StreamingTV tiene 0 duplicados y 0 nulos
la columna : StreamingMovies tiene 0 duplicados y 0 nulos
la columna : Contract tiene 0 duplicados y 0 nulos
la columna : PaperlessBilling tiene 0 duplicados y 0 nulos
la columna : PaymentMethod tiene 0 duplicados y 0 nulos
la columna : MonthlyCharges tiene 0 duplicados y 0 nulos
la columna : TotalCharges tiene 0 duplicados y 0 nulos
la columna : Churn tiene 0 duplicados y 0 nulos

In [47]:
for column in customer_df.select_dtypes(include="object").columns :
    empty = customer_df[column].str.strip().eq("").sum()
    if empty > 0:
        print(f"la columna {column} cuenta con : {empty}, valores vacios vacias")

la columna TotalCharges cuenta con : 11, valores vacios vacias

C:\Users\Usuario\AppData\Local\Temp\ipykernel_2348\1572800514.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in customer_df.select_dtypes(include="object").columns :

In [48]:
CantidadVacia = customer_df["TotalCharges"].str.strip().eq("").sum()
Total = customer_df["TotalCharges"].shape[0]

print(f"el porcentaje de datos vacios son :{((CantidadVacia/Total)*100).round(2)} %")

el porcentaje de datos vacios son :0.16 %

In [49]:
customer_df.loc[
    customer_df["TotalCharges"].str.strip().eq(""),
    ["customerID","tenure","MonthlyCharges","TotalCharges", "Contract", "Churn"]
]

      customerID  tenure  MonthlyCharges TotalCharges  Contract Churn
488   4472-LVYGI       0           52.55               Two year    No
753   3115-CZMZD       0           20.25               Two year    No
936   5709-LVOEQ       0           80.85               Two year    No
1082  4367-NUYAO       0           25.75               Two year    No
1340  1371-DWPAZ       0           56.05               Two year    No
3331  7644-OMVMY       0           19.85               Two year    No
3826  3213-VVOLG       0           25.35               Two year    No
4380  2520-SGTTA       0           20.00               Two year    No
5218  2923-ARZLG       0           19.70               One year    No
6670  4075-WKNIU       0           73.35               Two year    No
6754  2775-SEFEE       0           61.90               Two year    No

In [50]:
customer_df["TotalCharges"] = customer_df["TotalCharges"].replace(" ", np.nan)
customer_df["TotalCharges"].isna().sum()

np.int64(11)

In [51]:
customer_df["TotalCharges"] = customer_df["TotalCharges"].astype(float)
customer_df["TotalCharges"].dtype

dtype('float64')

In [52]:
customer_df = customer_df.dropna(subset=["TotalCharges"])
customer_df = customer_df.reset_index(drop=True)
customer_df["TotalCharges"].isna().sum()

np.int64(0)

In [53]:
customer_df["SeniorCitizen"] = customer_df["SeniorCitizen"].replace({1:"Yes",0:"No"})

In [54]:
columnas_NIS = ["OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]

for columna in columnas_NIS:
    customer_df[columna] = customer_df[columna].replace({"No internet service":"No"})

In [55]:
columnas_NIS = ["OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]

for columna in columnas_NIS:
    empty = (customer_df[columna] == "No internet service").sum()
    print(f"{empty}")

0
0
0
0
0
0

In [56]:
Columa_Categoria = ["gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService", "InternetService", 
                    "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", 
                    "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod", "Churn"]
for column in Columa_Categoria:
    customer_df[column] = customer_df[column].astype("category")

customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   category
 2   SeniorCitizen     7032 non-null   category
 3   Partner           7032 non-null   category
 4   Dependents        7032 non-null   category
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   category
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   category
 9   OnlineSecurity    7032 non-null   category
 10  OnlineBackup      7032 non-null   category
 11  DeviceProtection  7032 non-null   category
 12  TechSupport       7032 non-null   category
 13  StreamingTV       7032 non-null   category
 14  StreamingMovies   7032 non-null   category
 15  Contract          7032 non-null   category
 16  PaperlessBilling  7032 non-null   category
 17  PaymentMethod     7032 non-null   category
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   category
dtypes: category(16), float64(2), int64(1), str(2)
memory usage: 385.0 KB